### ISSUE TITLE
[Help]: Is it possible to hide the switch for a particular panel?

### ISSUE THREAD

**Issue by maxacarvalho** [bezhanSalleh/filament-panel-switch#26]
### What happened?

I'd like to hide the panel for a particular panel. I could not find a way to do that.

Thanks.

### How to reproduce the bug

not applicable.

### Package Version

1.0.5

### PHP Version

8.3

### Laravel Version

10.0.0

**Comment by bezhanSalleh** [comment]
https://spatie.be/docs/laravel-permission/v6/introduction

**Comment by willcastillo** [comment]
Hey... FWIW, it'd be nice to have the counterpart of `excludes`. Sometimes it would make sense to include a few panels (or just one, for instance)

**Comment by bezhanSalleh** [comment]
> Hey... FWIW, it'd be nice to have the counterpart of `excludes`. Sometimes it would make sense to include a few panels (or just one, for instance)

All the panels are included by default, and almost all of the configuration methods also accepts a closure to give devs more control.

For a single panel the switch won't make any sense. But if you have more to exclude then include! For instance if you have 8 panels and only want to include 2 then you could do just that:
```php
PanelSwitch::configureUsing(function (PanelSwitch $panelSwitch) {
    $panelSwitch->excludes(
      fn (): array => collect(Filament::getPanels())
           ->reject(
               fn (Panel $panel) => in_array($panel->getId(), ['admin', 'sass'])
            )
           ->toArray()
    );
});
```
hope this makes it clear. let me know if you have any questions.

**Comment by willcastillo** [comment]
Thanks @bezhanSalleh. Having one or even zero panels does make sense in some cases. For instance, when you assign panels dynamically for whatever reason.

I know using `excludes` could solve the use case, I just think it could be cleaner (or at the very least more versatile) to have both options. Prolly just me but I'd rather go with positive logic instead of checking for the negative space of a condition.

**Comment by bezhanSalleh** [comment]
> Thanks @bezhanSalleh. Having one or even zero panels (used together with `visible()`) does make sense in some cases. For instance, when you assign panels dynamically for whatever reason.
> 
> I know using `excludes` could solve the use case, I just think it could be cleaner (or at the very least more versatile) to have both options. Prolly just me but I'd rather go with positive logic instead of checking for the negative space of a condition.

NP... though Positive logic is the default, but i do get what you mean. I will `include` 😉 it in the next release. Anyhow, for now what you can do is to just extend `PanelSwitch` class and override the `getPanels()` method or maybe something like below
```php
declare(strict_types=1);

namespace App\Overrides;

use Closure;
use Filament\Panel;
use BezhanSalleh\PanelSwitch\PanelSwitch;

class PanelSwitchOverride extends PanelSwitch
{
    protected array | Closure $includes = [];

    public function includes(array | Closure $panelIds): static
    {
        $this->includes = $panelIds;

        return $this;
    }

    public function getIncludes(): array
    {
        return (array) $this->evaluate($this->includes);
    }

    public function getPanels(): array
    {
        return collect(filament()->getPanels())
            // now the logic here will depend on your implementation
            // maybe even validate if the provided panelIds exist or not
            // 1. once excluded remove it even if included - exclusion is prioritized 
            // 2. if excluded but also included then don't remove it - inclusion is prioritized ✓
            ->reject(
                 fn (Panel $panel) => in_array($panel->getId(), $this->getExcludes()) 
                 && !in_array($panel->getId(), $this->getIncludes())
            )
            ->toArray();
    }
}
```
and in your `AppServiceProvider`
```php
use App\Overrides\PanelSwitchOverride;
use Illuminate\Support\ServiceProvider;
use BezhanSalleh\PanelSwitch\PanelSwitch;

class AppServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        $this->app->bind(PanelSwitch::class, PanelSwitchOverride::class);
    }

    public function boot(): void
    {
        PanelSwitch::configureUsing(function (PanelSwitch $switch) {
            $switch
                ->includes(['app', 'saas']) // saas panel will be listed since inclusion takes priority.
                ->excludes(['saas'])
                ...
                ;
        });
   }
}
```
🍻

**Comment by willcastillo** [comment]
Hey @bezhanSalleh , yeah, I did something similar to what you suggested. Glad to hear you are open to add this feature. Thanks!

Good catch on the precedence problem you mentioned in your code. Architectural wise, why don't you follow a fluent approach?
- Default state is exactly as it is today: Your plugin lists all the available panels as candidates to be shown.
- **Whenever** an `includes` call is made, those panels **become** the new candidates to be shown.
- Whenever an `excludes` call is made, those panels are excluded from the **candidates to be shown**. 

This way, the developer is 100% responsible of the panels that will be shown and you don't have to make any decision there (it's not your responsibility anyway). For instance, what happens if you do this `TextInput::make('test')->visible(false)->visible(true)` The last one takes precedence, right? IMO, your plugin needs to follow this pattern as well.

**Comment by bezhanSalleh** [comment]
it does follow the fluent pattern. anyhow, what i have landed on is to deprecate the `excludes()` method, not add another `includes()` method and let the developers do the inclusion and exclusion themselves via `panels()` method.

**Comment by shebaoting** [comment]
In AppServiceProvider, it's not possible to accurately get the panel id using filament()->getCurrentPanel()->getId(), so it's also not possible to make a particular panel not show this toggle button at all

**Comment by shebaoting** [comment]
> it does follow the fluent pattern. anyhow, what i have landed on is to deprecate the `excludes()` method, not add another `includes()` method and let the developers do the inclusion and exclusion themselves via `panels()` method.

In AppServiceProvider, it's not possible to accurately get the panel id using filament()->getCurrentPanel()->getId(), so it's also not possible to make a particular panel not show this toggle button at all
