### ISSUE TITLE
[Bug]: The model [App\Models\Role] does not have a relationship named []

### ISSUE THREAD

**Issue by aeq-dev** [bezhanSalleh/filament-panel-switch#29]
### What happened?

After upgrading this package to latest 1.0.6, I got this error : 
`The model [App\Models\Role] does not have a relationship named []. You can change the relationship being used by passing it to the [ownershipRelationship] argument of the [tenant()] method in configuration. You can change the relationship being used per-resource by setting it as the [$tenantOwnershipRelationshipName] static property on the [BezhanSalleh\FilamentShield\Resources\RoleResource] resource class.`

### How to reproduce the bug

Update composer, package upgraded from 1.0.5 to 1.0.6

### Package Version

1.0.6

### PHP Version

8.2

### Laravel Version

10.48.19

### Notes

Downgrade to previous version 1.0.5 works fine.

**Comment by bezhanSalleh** [comment]
Seems an issue with your shield config for multi tenancy not this plugin.

**Comment by lucassdoro** [comment]
Sorry @bezhanSalleh, but I have the same issue. I was able to make some progress with a few tests to help clarify the problem:

- I found that version 1.0.6 is affected by the issue, likely due to how it handles switching panels. It seems to occur only when transitioning from a non-multi-tenancy panel to one that is multi-tenancy.
- When I revert back to version 1.0.5, the issue disappears, but the routing problem that was fixed in the latest version reappears.
- I checked all the shield configurations, and they are correct.
- I have two panels set up, one with multi-tenancy and one without. When I uninstall the plugin, the reported error goes away.
Unfortunately, due to time constraints, I couldn’t conduct more tests, but I hope this information helps us find a solution or identify the issue.
